name: CI
on: 
  pull_request:
    branches: [develop]
  push:
    branches: [develop]


jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci 
      - run: nom run format:check
      - run: npm test -- --coverage
        env:
          CI: true
      - name: Build project
        if: github.event_name == 'push'
        run: npm run build 
      - name: Deploy to staging
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain roksejorma.surge.sh
        env:
          SURGE_LOGIN: ${{ secret.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secret.SURGE_TOKEN }}