name: CI
on: 
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci 
      - run: nom run format:check
      - run: npm test -- --coverage
        env:
          CI: true
      